# Generated by Django 5.2.5 on 2026-06-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='feedback/pictures')),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموقع')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/', verbose_name='شعار الموقع')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='رابط إنستغرام')),
            ],
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='مضيف SMTP')),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='منفذ SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستخدم SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة مرور SMTP')),
                ('use_tls', models.BooleanField(default=False, verbose_name='استخدام TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='استخدام SSL')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='stock_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_count', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('clothing', 'ملابس'), ('electronics', 'إلكترونيات'), ('home', 'منزلية'), ('kitchen', 'مطبخ'), ('health_beauty', 'صحة وجمال'), ('children', 'أطفال'), ('books', 'كتب'), ('sports', 'رياضة')], default='clothing', max_length=20)),
                ('uuid', models.CharField(default='0b4adf', editable=False, max_length=6, unique=True)),
                ('sizes', models.CharField(blank=True, help_text='Comma-separated sizes (e.g. S,M,L,XL)', max_length=255, null=True)),
                ('colors', models.CharField(blank=True, help_text='Comma-separated colors (e.g. #FF0000,#0000FF)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stock_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=150)),
                ('wilaya', models.CharField(default='', max_length=150)),
                ('commune', models.CharField(default='', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الإنتظار'), ('confirmed', 'تم التأكيد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'تم الإلغاء')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('association', 'جمعية'), ('organizer', 'منظم'), ('volunteer', 'متطوع'), ('participant', 'مشارك'), ('other', 'أخرى')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='dashboard.event')),
            ],
        ),
        migrations.CreateModel(
            name='userNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('icon', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار المستخدم',
                'verbose_name_plural': 'إشعارات المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
