# Generated by Django 5.2.5 on 2026-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='09f5b4', editable=False, max_length=6, unique=True),
        ),
    ]
