# Generated by Django 5.2.5 on 2026-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_stock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='0fc472', editable=False, max_length=6, unique=True),
        ),
    ]
