# Generated by Django 5.2.5 on 2026-06-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_stock_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='SMTPSettings',
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='38d711', editable=False, max_length=6, unique=True),
        ),
    ]
