# Generated by Django 5.2.5 on 2026-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_sitesettings_delete_smtpsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='7b7737', editable=False, max_length=6, unique=True),
        ),
    ]
