# Generated by Django 5.2.5 on 2026-06-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_stock_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='dbc225', editable=False, max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('wilaya', models.CharField(blank=True, choices=[('01', 'أدرار'), ('02', ' الشلف'), ('03', 'الأغواط'), ('04', 'أم البواقي'), ('05', 'باتنة'), ('06', ' بجاية'), ('07', 'بسكرة'), ('08', 'بشار'), ('09', 'البليدة'), ('10', 'البويرة'), ('11', 'تمنراست'), ('12', 'تبسة'), ('13', 'تلمسان'), ('14', 'تيارت'), ('15', 'تيزي وزو'), ('16', 'الجزائر'), ('17', 'الجلفة'), ('18', 'جيجل'), ('19', 'سطيف'), ('20', 'سعيدة'), ('21', 'سكيكدة'), ('22', 'سيدي بلعباس'), ('23', 'عنابة'), ('24', 'قالمة'), ('25', 'قسنطينة'), ('26', 'المدية'), ('27', 'مستغانم'), ('28', 'المسيلة'), ('29', 'معسكر'), ('30', 'ورقلة'), ('31', 'وهران'), ('32', 'البيض'), ('33', 'إليزي'), ('34', 'برج بوعريريج'), ('35', 'بومرداس'), ('36', 'الطارف'), ('37', 'تندوف'), ('38', 'تيسمسيلت'), ('39', 'الوادي'), ('40', 'خنشلة'), ('41', 'سوق أهراس'), ('42', 'تيبازة'), ('43', 'ميلة'), ('44', 'عين الدفلة'), ('45', 'النعامة'), ('46', 'عين تيموشنت'), ('47', 'غرداية'), ('48', 'غليزان'), ('49', 'تيميمون'), ('50', 'برج باجي مختار'), ('51', 'أولاد جلال'), ('52', 'بني عباس'), ('53', 'عين صالح'), ('54', 'عين قزام'), ('55', 'تقرت'), ('56', 'جانت'), ('57', 'المغير'), ('58', 'المنيعة')], max_length=100, verbose_name='الولاية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
