# Generated by Django 5.2.5 on 2026-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_stock_uuid_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='9a37e0', editable=False, max_length=6, unique=True),
        ),
    ]
