# Generated by Django 5.2.5 on 2026-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_stock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='d526cb', editable=False, max_length=6, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('event', 'email'), ('event', 'phone')},
        ),
    ]
