# Generated by Django 5.2.5 on 2026-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_stock_uuid_alter_subscriber_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='666bd5', editable=False, max_length=6, unique=True),
        ),
    ]
