# Generated by Django 5.2.5 on 2026-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_usernotification_url_alter_stock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='e93b80', editable=False, max_length=6, unique=True),
        ),
    ]
