# Generated by Django 5.2.5 on 2026-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_stock_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=200, verbose_name='اسم الجمعية')),
                ('president_first_name', models.CharField(max_length=100, verbose_name='اسم الرئيس')),
                ('president_last_name', models.CharField(max_length=100, verbose_name='لقب الرئيس')),
                ('association_type', models.CharField(choices=[('local', 'محلية'), ('wilaya', 'ولائية'), ('rabita', 'رابطة')], max_length=20, verbose_name='نوع الجمعية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('registration_doc', models.FileField(upload_to='association_docs/', verbose_name='وثيقة التسجيل')),
                ('id_card', models.FileField(upload_to='association_id_cards/', verbose_name='بطاقة التعريف')),
                ('subscribe_newsletter', models.BooleanField(default=False, verbose_name='الاشتراك في النشرة البريدية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب انضمام جمعية',
                'verbose_name_plural': 'طلبات انضمام الجمعيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='5e59d6', editable=False, max_length=6, unique=True),
        ),
    ]
