# Generated by Django 5.2.5 on 2026-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_stock_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مشترك في النشرة البريدية',
                'verbose_name_plural': 'المشتركين في النشرة البريدية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='531e42', editable=False, max_length=6, unique=True),
        ),
    ]
