# Generated by Django 5.2.5 on 2026-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_stock_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='اللقب'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='role',
            field=models.CharField(default='', max_length=100, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='93b1c0', editable=False, max_length=6, unique=True),
        ),
    ]
