# Generated by Django 5.2.5 on 2026-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_newslettersubscription_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='60832d', editable=False, max_length=6, unique=True),
        ),
    ]
