# Generated by Django 5.2.5 on 2026-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_delete_associationregistration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='stock',
            name='uuid',
            field=models.CharField(default='c26ca9', editable=False, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
